# Generated by Django 5.0.3 on 2024-06-07 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('duels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user_2', to=settings.AUTH_USER_MODEL, verbose_name='User 2'),
        ),
        migrations.AddField(
            model_name='chats',
            name='duel',
            field=models.ForeignKey(limit_choices_to={'status': 'contesting'}, on_delete=django.db.models.deletion.CASCADE, to='duels.duels', verbose_name='Duel'),
        ),
        migrations.AddField(
            model_name='chats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user_1', to=settings.AUTH_USER_MODEL, verbose_name='User 1'),
        ),
        migrations.AddField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chats'),
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
