# Generated by Django 5.0.3 on 2024-06-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('player_1_ready', models.BooleanField(default=False)),
                ('player_2_ready', models.BooleanField(default=False)),
                ('player_1_is_winner', models.BooleanField(blank=True, null=True)),
                ('player_2_is_winner', models.BooleanField(blank=True, null=True)),
                ('player_1_bet', models.PositiveIntegerField(default=0)),
                ('player_2_bet', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('started', 'Started'), ('contesting', 'Contesting')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Duel',
                'verbose_name_plural': 'Duels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField()),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
            },
        ),
    ]
