# Generated by Django 5.0.3 on 2024-06-08 23:01

import duels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duels',
            name='completed_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duels',
            name='created_at',
            field=models.IntegerField(default=duels.models.get_current_unix_time),
        ),
        migrations.AlterField(
            model_name='duels',
            name='pending_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duels',
            name='started_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='image',
            field=models.FileField(upload_to='maps/%Y-%m-%d-%h-%m-%s/'),
        ),
    ]
